### ISSUE TITLE
Debugging help

### ISSUE THREAD

**Issue by 42Bastian** [laoo/Felix#10] opened 2021-10-29 13:49 UTC
Not sure if it is possible, but a nice debugging feature would be to have hooks that can be used with Lua.
For example, before writing some memory, a `byte MemoryWrite(address, value)` function will be called if exist.
A Lua script might then do for example tracing of certain addresses or even modify the value to be written.
Same for examp,e `nextInstruction(address)`.
Can be used to implement custom break and watch points.

**Comment by laoo** [comment] 2021-10-29 20:44
That's the very reason for embedding lua interpreter. I wan't to have such features, I'm just not there yet.
I think that your proposed approach, though generic, would be too slow to be practical - going to lua each CPU cycle would be certainly a performace killer.
I have few ideas, I'm not sure what would be the best, but the simple one that can be done in reasonable time-frame is such that every memory location could be 32-bit long. 8 bit of data and 24 bit of attributes. These 3 bytes woule be three separate attributes for reading, writing and executing. Each memory access I could check corresponding attribute and if it's non-zero I would treat it as an index to a lua-function table to be called. So there would be a possibility to install in lua script up to 255 hooks for R/W/X separately and install any hook in any memory location.

**Comment by 42Bastian** [comment] 2021-10-30 07:34
If you want to catch Suzy writes, than yes we need to differ between Suzy/CPU. But I think this would be "Sprite debugging" and for this there are maybe better ways.
What is not clear to me is the 4th, the data byte. What data should it contain? The other part sounds great. Makes it easy to place any type of watchpoint or breakpoint.
But it would be great if the hook can manipulate the system, means changing any memory or register.

**Comment by laoo** [comment] 2021-11-22 07:54
@42Bastian I've added global RAM pointer. Hopefully to be obsoleted by lua facilities.

**Comment by laoo** [comment] 2021-11-24 17:38
@42Bastian: Added preliminary [Script debugger](https://github.com/laoo/Felix/wiki/Script-Debugger)

**Comment by laoo** [comment] 2021-11-29 15:34
### Breaking change
Now lua scripts must not specify image file and can't be run by emulator, but must be named as image file but with `.lua` extension suffix and are loaded automatically if present. For example with file `test.lnx` there can be associated a file `test.lnx.lua` with lua code, trap functions etc. The `image` variable is not used.

**Comment by laoo** [comment] 2022-01-05 10:29
Duplicate of #91

**Closed by laoo** 2022-01-05 10:29 UTC
Labels: enhancement
