### ISSUE TITLE
General hardware collision problem

### ISSUE THREAD

**Issue by mikerro** [laoo/Felix#63] opened 2021-11-07 09:22 UTC
![Collision01 Sprdemo05](https://user-images.githubusercontent.com/24191730/140637739-37cada87-9367-49ef-9147-9344c05d0d51.png)
(objects get bigger when sprite collision occures)

**Comment by laoo** [comment] 2021-11-12 05:56
Fixed in 0.4.6

**Comment by 42Bastian** [comment] 2021-11-12 06:05
Maybe reopen as  https://github.com/42Bastian/new_bll/blob/master/demos/boing.o does not work.
Some "balls" collide in the middle w/o any contact.

**Comment by laoo** [comment] 2021-11-12 06:42
Sorry, I haven't pushed it yet. I should have waited with closing untill push.
I'll check boing.o too
I haven't pushed because flappy bird still does not work and I'm searching the cause.

**Comment by laoo** [comment] 2021-11-12 07:00
@42Bastian Pushed, that I've fixed so far, but still there are problems

**Comment by 42Bastian** [comment] 2021-11-12 07:58
I try to get what you are doing, but honestly, it looks overly complicated. I have to admit I do not really understand what you are doing. For example, why you take the pixel color into account for the position of the mask?!
`  size_t idx = mSpriteType * ColOperator::POSSIBLE_PIXELS + pixel;`

**Comment by 42Bastian** [comment] 2021-11-12 09:34
I suspect the problem here `void ColOperator::receiveHiColl( uint32_t value )` because mColl is only uint16_t.
I tried to expand it to uint32_t and all the related structs, but no success.

**Comment by laoo** [comment] 2021-11-12 09:48
The algorithm might be overcomplicated. I'm simplifying it a little and I'll write how it works.

**Comment by laoo** [comment] 2021-11-12 09:51
mColl is 16 bit but it's duplicated in during collision RMW operation: 

https://github.com/laoo/Felix/blob/6e8995ec9d5aea43272c1fd6c5c59c2befdbe861/libFelix/Core.cpp#L275-L276

**Comment by 42Bastian** [comment] 2021-11-12 10:01
Just found it :-) Attached a version of boing.o with a single "ball". So collision happens only with the walls.
[boing.zip](https://github.com/laoo/Felix/files/7526673/boing.zip)

**Comment by laoo** [comment] 2021-11-12 10:03
Thanks! I'll work with it

**Comment by laoo** [comment] 2021-11-12 10:05
Renamed to general collision problem and reopened

**Comment by laoo** [comment] 2021-11-12 11:39
@42Bastian Thanks to your simplified example I've found the bug:

https://github.com/laoo/Felix/blob/6e8995ec9d5aea43272c1fd6c5c59c2befdbe861/libFelix/Core.cpp#L278-L281

I was sending to collision depository ("fred") the value read from the collision buffer **after** combining it with new collision value.

**Comment by laoo** [comment] 2021-11-12 11:57
I've simplified the algorithm and it can be described as follows.
There is a struct template
https://github.com/laoo/Felix/blob/cd7715038c37bc454461ccb0a310c6f284c63d8b/libFelix/SpriteTemplates.hpp#L4-L7
with all sprite properties that is concretized for each sprite type, e.g.:
https://github.com/laoo/Felix/blob/cd7715038c37bc454461ccb0a310c6f284c63d8b/libFelix/SpriteTemplates.hpp#L10-L31

Mask for given pixel position in set, if the color of written pixel is collideable within given spirte type. After refactoring and simplification I have got a two-dimensional boolean table whether each pixel of each sprite type is collideable.
https://github.com/laoo/Felix/blob/cd7715038c37bc454461ccb0a310c6f284c63d8b/libFelix/ColOperator.cpp#L10
In `ColOperator` constructor I'm selecting a table for given sprite type of all pixel values to check if given pixel is collideable and I'm using it to determine whether to set mask for given pixel
https://github.com/laoo/Felix/blob/cd7715038c37bc454461ccb0a310c6f284c63d8b/libFelix/ColOperator.cpp#L225

**Comment by laoo** [comment] 2021-11-12 11:59
Now it's better, but flappy bird still does not work. I'm searching the problem.

**Comment by 42Bastian** [comment] 2021-11-12 12:15
" if the color of written pixel is collideable within given spirte type."
It is not the color it is the pen!

**Comment by laoo** [comment] 2021-11-12 12:52
You're right! Stupid mistake!

Although flappy bird is stubbor, and it still does not work. Still searching

**Comment by 42Bastian** [comment] 2021-11-12 12:57
In one game (not sure which) I saw transparent pixel, where should not be. Also, did you check for the 'E' bug?

**Comment by 42Bastian** [comment] 2021-11-12 13:05
Here two examples with a ball only going horizontal with vertical walls at x = 57 and x = 60.
[boing.zip](https://github.com/laoo/Felix/files/7527710/boing.zip)

**Comment by laoo** [comment] 2021-11-12 13:58
I'm now away of computer but it's likely a bug that in RMW operation I send back unmasked value from collision buffer and it should be masked. You can try that, I'll fix it when I'm back home.

**Comment by laoo** [comment] 2021-11-12 13:59
I must have accidenally closed this :)

**Closed** 2021-11-12 18:30 UTC

**Comment by laoo** [comment] 2021-11-12 19:27
Found the bug:
https://github.com/laoo/Felix/blob/469b76ccc70ad4caa90596d56c8176c14388bce3/libFelix/Core.cpp#L278-L280
The value that should have been sent back isn't `value` nor `maskedValue` but `outValue` which has selected nibbles that will be overwritten.
Now everything seems to be working

**Comment by laoo** [comment] 2021-11-12 19:58
Actually there was a misunderstanding and I lost the difference of _pen index_ and _pen number_. All should be fixed now.
